name: DeathMessages
version: ${version}
main: dev.mrshawn.deathmessages.DeathMessages
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - DiscordSRV
  - MythicMobs
  - CombatLogX
  - eco
  - EcoEnchants
  - LangUtils
  - SayanVanish
authors:
  - CosmoConsole
  - Joshb_
  - MrShawn
  - Dreeam-qwq
libraries:
  - ${depAdventurePlatformBukkit}
  - ${depAdventureApi}
  - ${depAdventureTextMinimessage}
  - ${depAdventureTextSerializerLegacy}
  - ${depAdventureTextSerializerPlain}
  - ${depAdventureTextSerializerGson}
  - ${depAdventureKey}
commands:
  deathmessages:
    description: Main DeathMessages command
    aliases: [ dm ]
  deathmessagestoggle:
    description: Alias for /dm toggle in one command
    aliases: [ dmt, dmtoggle, toggledeathmsgs]
